version: "3"
services:
  clash:
    image: laoyutang/clash-and-dashboard:latest
    container_name: clash
    privileged: true
    hostname: clash
    restart: unless-stopped
    ports:
      - "7890:7890"
      - "7891:7891"
      - "7892:7892"
      - "8080:8080"
    volumes:
      - /home/nas/clash/cloudflare.yaml:/root/.config/clash/config.yaml