version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    network_mode: host
    privileged: true
    command: tunnel --no-autoupdate run --token eyJhIjoiM2JhM2MzODc5N2I5Y2QwMmE3YWFjNzkzNjM5ZWRkODkiLCJ0IjoiODEwMDAxNmItMDI3Yy00M2RmLTllMjgtMmYyNDMwMGIyY2M5IiwicyI6IlkyTXlaak5sWlRZdE56Z3pZeTAwTTJJekxUZ3laRGt0WlRNMk5ESmlOMlUyWkdRNCJ9