version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    privileged: true
    ports:
      - "8096:8096"
    volumes:
      - /home/jellyfin/config:/config
      - /home/jellyfin/cache:/cache
      - /mnt:/mnt
