# emby
[[proxies]]
name = "emby"
type = "http"
localIP = "127.0.0.1"
localPort = 8096
customDomains = ["emby.gpg123.cn"]

# video
[[proxies]]
name = "fn-video"
type = "http"
localIP = "127.0.0.1"
localPort = 8005
customDomains = ["video.gpg123.cn","video1.gpg123.cn","video2.gpg123.cn","video3.gpg123.cn","video4.gpg123.cn","video5.gpg123.cn"]

# video
[[proxies]]
name = "jellyfin-video-server"
type = "http"
localIP = "127.0.0.1"
localPort = 8096
customDomains = ["jf-video.gpg123.cn","jf-video1.gpg123.cn","jf-video2.gpg123.cn","jf-video3.gpg123.cn"]

# 相册
[[proxies]]
name = "fn-picture"
type = "http"
localIP = "127.0.0.1"
localPort = 8006
customDomains = ["picture.gpg123.cn","picture1.gpg123.cn","picture2.gpg123.cn","picture3.gpg123.cn"]

#飞牛
[[proxies]]
name = "feiniu-nas"
type = "http"
localIP = "127.0.0.1"
localPort = 5666
customDomains = ["gpg123.cn"]

#prometheus
[[proxies]]
name = "prometheus"
type = "http"
localIP = "127.0.0.1"
localPort = 9090
customDomains = ["prometheus.gpg123.cn"]

#prometheus-alert
[[proxies]]
name = "prometheus-alert"
type = "http"
localIP = "127.0.0.1"
localPort = 9093
customDomains = ["prometheus-alert.gpg123.cn","alert.gpg123.cn"]

#node-exporter
[[proxies]]
name = "node-exporter"
type = "http"
localIP = "127.0.0.1"
localPort = 9100
customDomains = ["node-exporter.gpg123.cn"]

#amd-smi-exporter
[[proxies]]
name = "amd-smi-exporter"
type = "http"
localIP = "192.168.3.15"
localPort = 2021
customDomains = ["amd-smi-exporter.gpg123.cn"]

#amd-gpu-exporter
[[proxies]]
name = "amd-gpu-exporter"
type = "http"
localIP = "192.168.3.15"
localPort = 5000
customDomains = ["amd-gpu-exporter.gpg123.cn"]

#windows-exporter
[[proxies]]
name = "windows-exporter"
type = "http"
localIP = "192.168.3.15"
localPort = 9182
customDomains = ["windows-exporter.gpg123.cn"]

#kube-state-metrics
[[proxies]]
name = "kube-state-metrics"
type = "http"
localIP = "127.0.0.1"
localPort = 8086
customDomains = ["kube-state-metrics.gpg123.cn"]

#black-box
[[proxies]]
name = "black-box"
type = "http"
localIP = "127.0.0.1"
localPort = 9115
customDomains = ["black-box.gpg123.cn"]

#cloud-server
[[proxies]]
name = "cloud-server"
type = "http"
localIP = "192.168.3.6"
localPort = 9099
customDomains = ["cloud-server.gpg123.cn"]

#stableDiffusion
[[proxies]]
name = "stableDiffusion"
type = "http"
localIP = "192.168.3.18"
localPort = 7860
customDomains = ["sd.gpg123.cn"]

#fileCodeBox
[[proxies]]
name = "filebox"
type = "http"
localIP = "127.0.0.1"
localPort = 12345
customDomains = ["filebox.gpg123.cn"]