#400G
[[proxies]]
name = "smb_share_feiniu"
type = "tcp"
remotePort = 6001
[proxies.plugin]
type = "static_file"
localPath = "/vol00/WDC WD4000FYYZ-01UL1B3"
stripPrefix = ""
httpUser = "test"
httpPassword = "test1234"

# data
[[proxies]]
name = "smb_share_data"
type = "tcp"
remotePort = 6002
[proxies.plugin]
type = "static_file"
localPath = "/vol1/1000"
stripPrefix = ""

#aliyunpan
[[proxies]]
name = "smb_share_aliyunpan"
type = "tcp"
remotePort = 6003
[proxies.plugin]
type = "static_file"
localPath = "/vol02/1000-1-7c388700"
stripPrefix = ""

#smb
[[proxies]]
name = "smb"
type = "tcp"
# SMB 服务器的内网 IP 和端口
localIP = "127.0.0.1"
localPort = 445
# 服务器映射的端口（不能是 445，选个没被占用的，如 4450）
remotePort = 4455
#sudo mount -t cifs -o port=4450 //你的服务器IP/share /mnt/local_folder